#**NumPy basic:-**

**- This convert the list into numpy array**

In [ ]:
# code example

import numpy as np

# normal python list
list_data= [1,2,3,4]


#NumPy array (ndarray)
arr = np.array([1,2,3,4])

print("list:",list_data)
print("array:",arr)
print("Type of list data:",type(list_data))
print("Type of array:",type(arr))

list: [1, 2, 3, 4]
array: [1 2 3 4]
Type of list data: <class 'list'>
Type of array: <class 'numpy.ndarray'>


#**Array creation:-**
**- create an array from python list/tuple**

In [ ]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
import numpy as np

arr=np.array([70,80,90,100])
print(arr)
print("shape",arr.shape)
print("dimension:",arr.ndim)

[ 70  80  90 100]
shape (4,)
dimension: 1


In [ ]:
import numpy as np

arr1 = [ [10,20,30],
         [40,50,60]]
arr1=np.array([[10,20,30],
               [40,50,60]])
print(arr1)
print(arr1.shape)




[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
# question no 1.

import numpy as np

arr = np.array([
               [1,2],
               [3,4],
               [5,6]
               ])
print(arr.shape)


(3, 2)


In [ ]:
# question no 2.

import numpy as np

arr = np.array([
                [5,10,15],
                [20,25,30],
                [35,40,45]
                ])
print(arr.shape)
print(arr)


(3, 3)
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
# question no 5.

import numpy as np
arr=np.array([[2,4,6,8],
              [10,12,14,16]
              ])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

arr=np.array(["A","B","C"])
arr1=np.array([""])
print(arr+arr1)

['pintusharma']


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1.0,2.10,3.5])
c = np.array(["a","b","c","d"])

print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
<U1


In [ ]:
l = [1,2,3,4,5]

arr=np.array(l,dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
l = ([1,2,3,4,5])

arr = np.array(l,dtype=str)
print(arr)

['1' '2' '3' '4' '5']


In [ ]:
l=[1.10,2.56,3.44]
arr=np.array(l,dtype=int)
print(arr)

[1 2 3]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([1.0,2.10,3.5])
c=np.array([True,False,True,False])
d=np.array(["1","2","3"])

print(a.astype(float))
print(a.astype(str))

print(b.astype(int))

print(c.astype(int))
print(c.astype(str))

print(d.astype(float))
print(d.astype(int))

[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[1 2 3]
[1 0 1 0]
['True' 'False' 'True' 'False']
[1. 2. 3.]
[1 2 3]


#**Shaping in 3-Dimensional Array:-**

In [ ]:
arr=np.array([[
             [1,2,3,4],
             [4,5,6,7],
             [8,9,10,11]
             ]])
print(arr.ndim)
print(arr)

3
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [ ]:
import numpy as np

arr=np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
    [10,11,12]]
])

print(arr.shape)
print(arr.ndim)

(2, 2, 3)
3


In [ ]:
import numpy as np

arr=np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ],
    [
        [17,18,19,20],
        [21,22,23,24]
    ]
])

print(arr.shape)
print(arr.ndim)



(3, 2, 4)
3


In [ ]:
import numpy as np

arr=np.array([
    [
        [2,4,6],
        [8,10,12],
        [14,16,18]
    ],

    [
        [20,22,24],
        [26,28,30],
        [32,34,36]
    ]
])

print(arr.shape)
print(arr.ndim)

(2, 3, 3)
3


In [ ]:
import numpy as np

arr=np.array([[[1,2,3,4],
              [5,6,7,8]],


             [[9,10,11,12],
              [13,14,15,16]],


             [[17,18,19,20],
              [21,22,23,24]]])

print(arr)
print(arr.shape)






[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
(3, 2, 4)


In [ ]:
import numpy as np

arr = np.array([[[5,10,15],
                [20,25,30],
                [35,40,45]],

               [[50,55,60],
                [65,70,75],
                [80,85,90]]])

print(arr)
print(arr.shape)

[[[ 5 10 15]
  [20 25 30]
  [35 40 45]]

 [[50 55 60]
  [65 70 75]
  [80 85 90]]]
(2, 3, 3)


In [ ]:
import numpy as np

arr = np.array([[[1,2,3,4],
               [5,6,7,8]],

               [[9,10,11,12],
                [13,14,15,16]],

               [[17,18,19,20],
                [21,22,23,24]]])

print(arr)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
(3, 2, 4)


In [ ]:
import numpy as np

arr = np.array([[[2,4,6,8,10],
                [12,14,16,18,20],
                [22,24,26,28,30],
                [32,34,36,38,40]],

               [[42,44,46,48,50],
                [52,54,56,58,60],
                [62,64,66,68,70],
                [72,74,76,78,80]],

               [[82,84,86,88,90],
                [92,94,96,98,100],
                [102,104,106,108,110],
                [112,114,116,118,120]]])
print(arr)
print(arr.shape)

[[[  2   4   6   8  10]
  [ 12  14  16  18  20]
  [ 22  24  26  28  30]
  [ 32  34  36  38  40]]

 [[ 42  44  46  48  50]
  [ 52  54  56  58  60]
  [ 62  64  66  68  70]
  [ 72  74  76  78  80]]

 [[ 82  84  86  88  90]
  [ 92  94  96  98 100]
  [102 104 106 108 110]
  [112 114 116 118 120]]]
(3, 4, 5)


In [ ]:
import numpy as np

arr = np.array([[[3,6,9,12],
                [15,18,21,24]],

               [[27,30,33,36],
                [39,42,45,48]],

               [[51,54,57,60],
                [63,66,69,72]]])
print(arr.shape)


(3, 2, 4)


#**4D**

In [ ]:
import numpy as np

arr=np.arange(96)
arr4d=arr.reshape(2,3,4,4)
print(arr4d)
print(arr4d.shape)
print(arr4d.ndim)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]
   [24 25 26 27]
   [28 29 30 31]]

  [[32 33 34 35]
   [36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]


 [[[48 49 50 51]
   [52 53 54 55]
   [56 57 58 59]
   [60 61 62 63]]

  [[64 65 66 67]
   [68 69 70 71]
   [72 73 74 75]
   [76 77 78 79]]

  [[80 81 82 83]
   [84 85 86 87]
   [88 89 90 91]
   [92 93 94 95]]]]
(2, 3, 4, 4)
4


In [ ]:
import numpy as np

arr=np.arange(48).reshape(2,2,3,4)
print(arr1)
print(arr[1][0][2][3])


[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
35


In [ ]:
import numpy as np

arr=np.arange(48).reshape(2,2,3,4)
print(arr[1][0].sum())
print(arr)

354
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


In [ ]:
import numpy as np

arr=np.arange(48).reshape(2,2,3,4)
print(arr)
print(arr[0][1][:])

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
import numpy as np

arr=np.arange(32).reshape(2,2,2,4)
arr1=arr.reshape(4,8)
print(arr)

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]]


 [[[16 17 18 19]
   [20 21 22 23]]

  [[24 25 26 27]
   [28 29 30 31]]]]


In [ ]:
import numpy as np

arr = np.array([[[3,6,9,12],
                [15,18,21,24]],

               [[27,30,33,36],
                [39,42,45,48]],

               [[51,54,57,60],
                [63,66,69,72]]])
print(arr[0,1,3])
print(arr[1,0,2])
print(arr[2,1,1])
print(arr[2,0,0])


24
33
66
51


In [ ]:
import numpy as np

arr=np.arange(18)
arr1=arr.reshape(3,-1)
print("Array reshaped into 3 rows")
print(arr1)

arr2=arr.reshape(6,-1)
print("Array is reshaped into 6 rows")
print(arr2)



Array reshaped into 3 rows
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Array is reshaped into 6 rows
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
import numpy as np

arr=np.arange(24)
arr1=arr.reshape(2,3,4)
print(arr1)

print(arr1.ndim)
print(arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(24,)


In [ ]:
import numpy as np

arr = np.array([[[1,2],
                [3,4]],

               [[7,8],
                [9,10]],

               [[12,13],
                [33,43]]])
print(arr.shape)
print(arr.si)



(3, 2, 2)


#**Data conversion:-**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr.astype(str))



['1' '2' '3' '4']


In [ ]:
import numpy as np

a=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])

b = a.astype(str)
print(b.astype(str))
print(b.dtype)



[['10' '20' '30']
 ['40' '50' '60']
 ['70' '80' '90']]
<U21


In [ ]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8]])
b=a.astype(str)
print(b.astype(str))
print(b.dtype)


[['1' '2' '3' '4']
 ['5' '6' '7' '8']]
<U21


In [ ]:
import numpy as np

a=np.array([[11,22,33],
            [44,55,66],
            [77,88,99]])
b=a.astype(str)
print(b.astype(str))
print(b.dtype)

[['11' '22' '33']
 ['44' '55' '66']
 ['77' '88' '99']]
<U21


In [ ]:
import numpy as np

my_list=[10,20.5,"hello",30,40.7]

arr=np.array(my_list)

print(arr)
print(arr.dtype)

['10' '20.5' 'hello' '30' '40.7']
<U32


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([1.0,2.10,3.5])
c=np.array([True,False,True,False])
d=np.array(["1","2","3"])

print(a.astype(float))
print(a.astype(str))

print(b.astype(int))

print(c.astype(int))
print(c.astype(str))

print(d.astype(float))
print(d.astype(int))

[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[1 2 3]
[1 0 1 0]
['True' 'False' 'True' 'False']
[1. 2. 3.]
[1 2 3]


In [ ]:
import numpy as np

a="25"

a=np.array(a)
print(a.astype(int))

25


In [ ]:
import numpy as np

b=12.9

b=np.array(b)
print(b.astype(int))

12


<class 'str'>
<class 'str'>


In [ ]:
import numpy as np

a=45.67

a=np.array(a)
print(a.astype(int))

45


In [ ]:
numbers=[5,10,15,20,25]

numbers=tuple(numbers)

print(numbers)
print(type(numbers))

(5, 10, 15, 20, 25)
<class 'tuple'>


In [ ]:
import numpy as np

values=(100,200,300,400)

values=list(values)
print(values)
print(type(values))

[100, 200, 300, 400]
<class 'list'>


In [ ]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr.astype(float))

[10. 20. 30. 40.]


In [ ]:
import numpy as np

arr=np.array([1.5,2.7,3.9,4.2])
print(arr.astype(int))
print(arr.astype(str))

[1 2 3 4]
['1.5' '2.7' '3.9' '4.2']


In [ ]:
import numpy as np

arr=np.array([5,10,15])
print(arr.dtype)

arr1=arr.astype(float)
print(arr1.dtype)

int64
float64


In [ ]:
import numpy as np

arr = np.array(["10","20","30","40"])
print(arr.astype(int))

[10 20 30 40]


In [ ]:
import numpy as np

arr=np.array([0,1,2,0,5])
print(arr.astype(bool))

[False  True  True False  True]


In [ ]:
import numpy as np

arr=np.array([1,0,1,0,1])
print(arr.astype(float))
print(arr.astype(str))
print(arr.astype(bool))

[1. 0. 1. 0. 1.]
['1' '0' '1' '0' '1']
[ True False  True False  True]


In [ ]:
import numpy as np

arr=np.array([[1,2],[3,4]])

arr_float=arr.astype(float)

print(arr_float)
print("Data type:",arr_float.dtype)


[[1. 2.]
 [3. 4.]]
Data type: float64


#**Reshape Array in NumPy:-**

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr=np.array([2,4,6,8,10,12,14,16])
arr1=arr.reshape(2,4)
print(arr1)

print("shape of reshape",arr1.shape)

arr2=arr.reshape(4,2)
print("reshape(4,2):")
print(arr2)

[[ 2  4  6  8]
 [10 12 14 16]]
shape of reshape (2, 4)
reshape(4,2):
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr=arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr=arr.reshape(5,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


**Arange in python**

In [ ]:
import numpy as np

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
import numpy as np

arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
import numpy as np

arr=np.arange(2,12,3)
print(arr)

[ 2  5  8 11]


#**Reshaping using (-1):-**

In [ ]:
import numpy as np

arr = np.arange(12)
new_arr=arr.reshape(3,-1)
print(new_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

arr = np.arange(12)
new_arr=arr.reshape(2,-1)
print(new_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
import numpy as np

arr=np.arange(18)
arr1=arr.reshape(3,-1)
print(arr1)

arr2=arr.reshape(6,-1)
print(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
import numpy as np

arr=np.array([[[1,2,3],
               [4,5,6]]],ndmin=5)
print(arr)

[[[[[1 2 3]
    [4 5 6]]]]]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])
new_arr=arr.reshape(3,3)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4))
print(arr.reshape(4,3))
print(arr.reshape(1,12))
print(arr.reshape(12,1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


#**Arange**

In [ ]:
import numpy as np

arr = np.arange(1,25)
print("Reshaped into 3D array:")
print(arr.reshape(3,2,4))

print("Reshaped into a 6D array:")
print(arr.reshape(2,2,3,2,1,1))

print("Reshaped into 4D array:")
print(arr.reshape())

Reshaped into 3D array:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
Reshaped into a 6D array:
[[[[[[ 1]]

    [[ 2]]]


   [[[ 3]]

    [[ 4]]]


   [[[ 5]]

    [[ 6]]]]



  [[[[ 7]]

    [[ 8]]]


   [[[ 9]]

    [[10]]]


   [[[11]]

    [[12]]]]]




 [[[[[13]]

    [[14]]]


   [[[15]]

    [[16]]]


   [[[17]]

    [[18]]]]



  [[[[19]]

    [[20]]]


   [[[21]]

    [[22]]]


   [[[23]]

    [[24]]]]]]


#**Linspace**

In [ ]:
import numpy as np

arr=np.linspace(0,10,5)
print(arr)

arr=np.linspace(0,10,4)
print(arr)


[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
import numpy as np

arr=np.arange(50,100)
arr1=np.linspace(50,100,10)
print(arr1)

[ 50.          55.55555556  61.11111111  66.66666667  72.22222222
  77.77777778  83.33333333  88.88888889  94.44444444 100.        ]


#**creating arrays with some values.**
**zeros**

In [ ]:
import numpy as np

arr=np.zeros(10)
print(arr)
print(arr.dtype)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [ ]:
import numpy as np

arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

arr=np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


**ones**

In [ ]:
import numpy as np

arr=np.ones((2,3,4))
print(arr)
print(arr.dtype)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64


**full**

In [ ]:
import numpy as np

arr=np.full((2,3,4),10)
print(arr)

[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


#**Identity matrix:-**

In [ ]:
import numpy as np

arr=np.identity(5)
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**eye:-**

In [ ]:
import numpy as np

arr=np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
import numpy as np

arr=np.eye(5,10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np

arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#**Indexing:-**

**slicing**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:9])

[4 5 6 7 8 9]


In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:3])

print(arr[0:2,1:])
print(arr[0:3:2,2:3:2])

[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[3]
 [9]]


#**Ndmin**

In [ ]:
import numpy as np

arr=np.array([1,2,3])
print(arr)
print(arr.ndim)




[1 2 3]
1


In [ ]:
import numpy as np

arr=np.array([1,2,3],ndmin=2)
print(arr)
print(arr.ndim)

[[1 2 3]]
2


In [ ]:
import numpy as np

arr=np.array([1,2,3],ndmin=3)
print(arr)
print(arr.ndim)

[[[1 2 3]]]
3


**Basics level question of Ndmin**

In [ ]:
# Question no 1

import numpy as np

arr=np.array([10,20,30],ndmin=2)
print(arr)
print(arr.ndim)


[[10 20 30]]
2


In [ ]:
# question no 2

import numpy as np

arr=np.array([1,2,3,4],ndmin=3)
print(arr)
print(arr.ndim)

[[[1 2 3 4]]]
3


In [ ]:
# question no 3

import numpy as np

arr=np.array([5,6,7],ndmin=4)
print(arr)
print(arr.ndim)

[[[[5 6 7]]]]
4


In [ ]:
# Question no 4

import numpy as np
arr=np.array([9,8,7],ndmin=1)
print(arr.ndim)

1


**intermmediate level question of ndmin**

In [ ]:
# question no 1

import numpy as np

arr=np.array([2,4,6,8,10],ndmin=3)
print(arr.shape)
print(arr.ndim)
print(arr)


(1, 1, 5)
3
[[[ 2  4  6  8 10]]]


In [ ]:
# question no 2

import numpy as np

arr1=np.array([1,2,3],ndmin=2)
arr2=np.array([1,2,3],ndmin=3)

print(arr1)
print(arr2)



[[1 2 3]]
[[[1 2 3]]]


In [ ]:
# question no 3.

import numpy as np

arr=np.array([[1,2,3]],ndmin=3)
print("Array:")
print(arr)

print("Number of Dimension:",arr.ndim)

if arr.ndim == 3:
  print("yes this is 3D Array")
else:
  print("This is not 3D array")



Array:
[[[1 2 3]]]
Number of Dimension: 3
yes this is 3D Array


In [ ]:
# Question no 4.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin=4)
print(arr.ndim)
print(arr.shape)
print(arr)

4
(1, 1, 1, 12)
[[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]


**coding question based on ndmin NumPy**

In [ ]:
# question no 1

import numpy as np

arr=np.array([4,5,6],ndmin=3)
print(arr.shape)


(1, 1, 3)


In [ ]:
# question no 2

import numpy as np

arr=np.array([10,20,30],ndmin=2)
print(arr.ndim)

2


In [ ]:
# question no 3

import numpy as np

arr=np.array([1,2,3,4],ndmin=3)
print(arr.shape)

(1, 1, 4)


In [ ]:
# Question no 4

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8],ndmin=4)

print("Array")
print(arr)

print("Dimension of array:",arr.ndim)

if arr.ndim==4:
  print("yes it is 4D array")
else:
  print("No it is not 4D array")

Array
[[[[1 2 3 4 5 6 7 8]]]]
Dimension of array: 4
yes it is 4D array


In [ ]:
# Question no 5

import numpy as np

arr=np.array([[1,2],[3,4]],ndmin=3)
print(arr.ndim)

3


In [ ]:
# question no 6

import numpy as np

arr = np.array([5,10,15],ndmin=4)
print(arr)
print(arr.shape)
print(arr.ndim)


[[[[ 5 10 15]]]]
(1, 1, 1, 3)
4


In [ ]:
# question no 7

import numpy as np

arr=np.array([100,200,300,400],ndmin=2)
print(arr)
print(arr.ndim)


[[100 200 300 400]]
2


#**4-D Reshape in NumPy**
**code example**

In [ ]:
import numpy as np

arr=np.arange(24)
arr4d=arr.reshape(2,2,3,2)
print(arr4d)
print("Dimension:",arr4d.ndim)

[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]
Dimension: 4


In [ ]:
# Question no 1

import numpy as np

arr=np.arange(48)
arr4d=arr.reshape(2,2,3,4)
print(arr4d)
print(arr4d.shape)
print(arr4d.ndim)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
(2, 2, 3, 4)
4


#**Reshape (-1) in NumPy:-**
**code example**

In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
new_arr=arr.reshape(-1)
print(new_arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr=np.arange(12)
new_arr=arr.reshape(3,-1)
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Question no 1

import numpy as np

arr=np.arange(24)
new_arr=arr.reshape(-1,4)

print(new_arr)
print(new_arr.shape)
print(new_arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)
2


#**Linspace:-**
**code example**

In [ ]:
import numpy as np

arr=np.linspace(10,2,5)
print(arr)

[10.  8.  6.  4.  2.]


In [ ]:
import numpy as np

arr=np.linspace(1,5,5)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np

arr=np.linspace(0,10,4)
print(arr)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
# question no 1

import numpy as np

arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# question no 2

import numpy as np

arr=np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]


#**Identity matrix**
**Code example:-**


In [ ]:
import numpy as np

arr=np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr=np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

arr=np.identity(2)
print(arr)

[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np

arr= np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np

i=np.identity(3)
a=np.identity(3)

print(i*a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#**Slicing:-**

In [ ]:
import numpy as np

arr=np.arange(12)
arr1=arr.reshape(2,3,2,1)
print(arr1)

[[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]

  [[10]
   [11]]]]


In [ ]:
import numpy as np

arr=np.array([[[[1],[3]],[[5],[7]],[[9],[11]]],[[[13],[15]],[[17],[19]],[[21],[23]]]])
print(arr[0,0:3:2,0])

[1 9]


#**Flatten**

In [ ]:
import numpy as np


arr2d=np.array([[1,2],[5,6],[7,8]])
print(arr.flatten())
print(arr2d)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[1 2]
 [5 6]
 [7 8]]


#**mathematical operation :-**

In [ ]:
import numpy as np

arr=np.array([1,2,3])
print(arr*2)

[2 4 6]


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([11,12,13,14,15])
print(a+b)

[12 14 16 18 20]


In [ ]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

arr3=np.concatenate((arr1,arr2))
print(arr3)




[ 1  2  3  4  5  6  7  8  9 10]


#**Broadcasting:-**


In [ ]:
import numpy as np

a=np.array([[1,2,3],
            [4,5,6]])

b = np.array([10,20,30])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

a= np.array([[5,5],
             [6,6],
             [7,7]])
b=np.array([10,20])
print(a+b)

[[15 25]
 [16 26]
 [17 27]]


#**Indexing with 4 dimensional Array:-**

In [ ]:
import numpy as np

arr=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
             [[[9,10],[11,12]],[[13,14],[15,16]]]])
print(arr)
print(arr[0,1,1,0])
print(arr[1,0,0,1])
print(arr[1,1,1,1])
print(arr[0,0,1,1])
print(arr[1,1,0,1])
print(arr[1,0,0,1])

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
7
10
16
4
14
10


#**Slicing:-**

In [ ]:
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [ ]:
import numpy as np

arr=np.array([10,20,30,40,50])
print(arr[0:5:2])

[10 30 50]


In [ ]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0:2,1:3])


[[2 3]
 [5 6]]


In [ ]:
import numpy as np

arr=np.array([[10,20,30,40],
              [50,60,70,80],
              [90,100,110,120],
              [130,140,150,160]])
print(arr[1:3,1:3])
print(arr[:,2])

[[ 60  70]
 [100 110]]
[ 30  70 110 150]


#**Flatten:-**

In [ ]:
import numpy as np

arr=np.array([[1,2,3,4],
              [5,6,7,11],
              [8,9,10,5]])
print(arr.flatten())


[ 1  2  3  4  5  6  7 11  8  9 10  5]


In [ ]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr.flatten())


[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

arr=np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

arr=np.array([[[[1,2],[3,4],[5,6],[7,8]],
             [[9,10],[11,12],[13,14],[15,16]]]])
print(arr.flatten())
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(1, 2, 4, 2)


In [ ]:
import numpy as np

arr1=np.array([[1,2,3],
               [4,5,6]])
print(arr1.flatten())

[1 2 3 4 5 6]


#**nditer:-**

In [ ]:
import numpy as np

arr=np.array([[1,2],[3,4]])
for i in np.nditer(arr):
  print(i)

1
2
3
4


In [ ]:
import numpy as np

arr=np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#**Concatenate:-**

In [ ]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[-1,-2],[-3,-4],[-5,-6]])

c=np.concatenate((a,b),axis=0)
print(c)


[[ 1  2 -1 -2]
 [ 3  4 -3 -4]
 [ 5  6 -5 -6]]


In [ ]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[-1,-2],[-3,-4],[-5,-6]])

c=np.concatenate((a,b),axis=1)
print(c)


[[ 1  2 -1 -2]
 [ 3  4 -3 -4]
 [ 5  6 -5 -6]]


 **1D Array:-**

In [ ]:
# question no 1

import numpy as np

x=np.array([1,2,3])
y=np.array([4,5,6])

print(np.concatenate((x,y),axis=0))

[1 2 3 4 5 6]


In [ ]:
# question no 2

import numpy as np

a=np.array([10,20,30])
b=np.array([40,50])

print(np.concatenate((a,b)))

[10 20 30 40 50]


In [ ]:
# Question no 3

import numpy as np

a=np.array([1,1,1])
b=np.array([2,2,2])
c=np.array([3,3,3])

print(np.concatenate((a,b,c),axis=0))

[1 1 1 2 2 2 3 3 3]


In [ ]:
# question no 4

import numpy as np

x=np.array([5])
y=np.array([6,7,8])

print(np.concatenate((x,y),axis=0))




[5 6 7 8]


In [ ]:
# Question no 5

import numpy as np


arr1=np.array([100,200])
arr2=np.array([300,400,500])

print(np.concatenate((arr1,arr2)))

[100 200 300 400 500]


**2D Array:-**

In [ ]:
# code example 1

import numpy as np

a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
print(np.concatenate((a,b),axis=1))


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# question no 1

import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Question no 2

import numpy as np

a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
print(np.concatenate((a,b),axis=1))

[[10 20 50 60]
 [30 40 70 80]]


In [ ]:
# Question no 3

import numpy as np

a=np.array([[2,4,6],
            [8,10,12]])
b=np.array([[1,3,5],
            [7,9,11]])
print(np.concatenate((a,b),axis=1))





[[ 2  4  6  1  3  5]
 [ 8 10 12  7  9 11]]


In [ ]:
# Question no 4

import numpy as np

a=np.array([[5,5],[6,6],[7,7]])
b=np.array([[1,2],[3,4],[5,6]])
print(np.concatenate((a,b),axis=0))

[[5 5]
 [6 6]
 [7 7]
 [1 2]
 [3 4]
 [5 6]]


**3D array:-**

In [ ]:
# example 1

import numpy as np

a=np.array([[[1,2],[3,4]]])
b=np.array([[[5,6],[7,8]]])
c=np.concatenate((a,b),axis=2)
print(c.shape)




[[[1 2 5 6]
  [3 4 7 8]]]
(1, 2, 4)


In [ ]:
# question no 1.

import numpy as np

a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=np.concatenate((a,b),axis=0)
print(c.shape)
print(c)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# question no 2

import numpy as np

a=np.array([[10,20],[30,60]])
b=np.array([[50,60],[70,80]])
c=np.concatenate((a,b),axis=1)
print(c.shape)
print(c)

(2, 4)
[[10 20 50 60]
 [30 60 70 80]]


In [ ]:
# Question no 3

import numpy as np

a=np.array([[[1,2],[3,4]]])
b=np.array([[[9,9],[8,8]]])
c=np.concatenate((a,b),axis=2)
print(a.shape)
print(b.shape)
print(c)
print(c.shape)

(1, 2, 2)
(1, 2, 2)
[[[1 2 9 9]
  [3 4 8 8]]]
(1, 2, 4)


#**STACK:-**
**a)vstack(vertical stack)**

**b)hstack(horizontal stack)**

**c)dstack(defth stack)**

**V-STACK**

In [ ]:
# code example
import numpy as np

a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**H-STACK**

In [ ]:
# code example

import numpy as np

a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**D-STACK**

In [ ]:
# code example

import numpy as np

a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

#**Practice question on NumPy:-**

In [ ]:
# Question no 1.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,3,14,15,16,17,18,19,20])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12  3 14 15 16 17 18 19 20]


In [ ]:
# Question no 2.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr.shape)
print(arr.ndim)

(20,)
1


In [ ]:
# Question no 3.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr1=arr.reshape(4,5)
print(arr1)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# Question no 4.

import numpy as np

arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
print(arr[0])
print(arr[3])
print(arr[1,2])


[1 2 3 4 5]
[16 17 18 19 20]
8


In [ ]:
# Question no 5.

import numpy as np

arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print("row 1-3=")
print(arr[0:3])

print("row 2-4=")
print(arr[:,1:4])

print("last 3 elements are:")
print(arr[3,2:5])



row 1-3=
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
row 2-4=
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]
last 3 elements are:
[18 19 20]


In [ ]:
# Question no 6.

import numpy as np

arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array(5)
arr3=np.array(10)
print(arr1*arr2+arr3)




[[15 20 25]
 [30 35 40]
 [45 50 55]]


In [ ]:
# Question no 7.

import numpy as np

arr=np.array([1,2,3,4,5])
print("Addition=")
print(arr+arr)

print("Substraction=")
print(arr-arr)

print("multiplication=")
print(arr*arr)

print("concatenation=")
print(np.concatenate((arr,arr)))

Addition=
[ 2  4  6  8 10]
Substraction=
[0 0 0 0 0]
multiplication=
[ 1  4  9 16 25]
concatenation=
[1 2 3 4 5 1 2 3 4 5]


In [ ]:
# Question no 8.

import numpy as np

arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
# Question no 9

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])
arr2=arr.astype(float)
print(arr2.dtype)

float64


In [ ]:
# Question no 10.

import numpy as np

arr=np.array([[1.1,2.4,3.7],
              [4.6,5.8,6.10],
              [7.88,8.98,9.23]])
arr1=arr.astype(int)
print(arr1.dtype)


int64


In [ ]:
# Question no 11.

import numpy as np

arr=np.array([1.34,10.43,44.62])
arr2=arr.astype(int)
print(arr2)
arr3=arr2*2
print(arr3)



[ 1 10 44]
[ 2 20 88]


In [ ]:
# Question no 12.

import numpy as np

arr= np.array([1,2.5,3,4.8])
print(arr.dtype)

float64


In [ ]:
# Question no 13.

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.astype(float))
print(arr.astype(str))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
['1' '2' '3' '4' '5' '6' '7' '8' '9']


In [ ]:
# Question no 14.

import numpy as np

arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Question no 15.

import numpy as np

arr=np.eye(4,k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# Question no 16.

import numpy as np

arr=np.eye(6)